# Generated by Django 2.1.7 on 2019-04-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personupload',
            name='imgname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personupload',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
