# Generated by Django 2.1.7 on 2019-05-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_bucket_bucketupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketupload',
            old_name='name',
            new_name='pname',
        ),
    ]
