# Generated by Django 2.1.7 on 2019-05-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190517_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
            ],
        ),
    ]
